name: aplicacionpadel
description: "Aplicacion de padel."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.8.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
